repos:

- repo: local
  hooks:
    - id: black
      name: Black
      entry: black
      language: system
      types: [python]
    - id: isort
      name: Isort
      entry: isort -y
      language: system
      types: [python]
    - id: flake8
      name: Flake8
      entry: flake8
      language: system
      types: [python]
