version: '3.8'
services:
    postgres14:
        image: postgres:14-alpine
        environment:
            - POSTGRES_DB=testdb
            - POSTGRES_USER=dbadmin
            - POSTGRES_PASSWORD=mintkaka2010
        ports:
            - 54014:5432

    mysql8:
        image: mysql:8
        environment:
            - MYSQL_DATABASE=testdb
            - MYSQL_USER=dbadmin
            - MYSQL_PASSWORD=mintkaka2010
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        ports:
            - 33063:3306

networks:
    default:
