version: '3.8'
services:
    db:
        image: postgres:10.7-alpine
        environment:
            - POSTGRES_DB=testdb
            - POSTGRES_USER=dbadmin
            - POSTGRES_PASSWORD=mintkaka2010
        ports:
            - 5432:5432

networks:
    default:
