site_name: GETL
nav:
    - Home: 'README.md'
    - installation.md
    - 'User Guide':
      - 'user-guide/intro.md'
      - 'user-guide/lift-def.md'
      - 'user-guide/file-registry.md'
      - 'user-guide/lift-job-blocks.md'
      - 'user-guide/transform-functions.md'
    - 'About':
      - 'CONTRIBUTING.md'
      - Issue Tracker: 'https://github.com/husqvarnagroup/GETL/issues'
      - 'CHANGELOG.md'
      - License: 'LICENSE.md'
theme: readthedocs
repo_url: https://github.com/husqvarnagroup/GETL
markdown_extensions:
    - def_list
plugins:
    - search
    - LiftBlock
    - RootFiles:
        files:
          - 'README.md'
          - 'CHANGELOG.md'
          - 'CONTRIBUTING.md'
          - 'LICENSE.md'

